#!/bin/sh -eux

cd "$UB_OBJECTDIR"

# The glibc supports kernel versions 3.2.0 and above only.
# Sun RPC is removed, use libtirpc + rpcsvc-proto
# nsl removed, use libnsl
# libcrypt removed, use libxcrypt

echo "slibdir=/usr/lib" >> configparms
echo "rtlddir=/usr/lib" >> configparms
echo "sbindir=/usr/bin" >> configparms
echo "rootsbindir=/usr/sbin" >> configparms

UB_CONFIGURE_DIR="$UB_COMPILEDIR" ub_configure \
    --libexecdir=/usr/lib \
	--with-headers=/usr/include \
	--enable-bind-now \
	--enable-cet \
	--enable-fortify-source \
	--enable-kernel=5.4.40 \
	--enable-lock-elision \
	--enable-stack-protector=strong \
	--disable-profile \
	--disable-werror \
	--disable-timezone-tools

ub_make \
	CFLAGS="-O2 -mtune=generic" \
	user-defined-trusted-dirs=/usr/local/lib
