#!/bin/sh -eux

# alapinstalláció
make DESTDIR="${UB_INSTALLDIR}" \
    CUPSSERVERROOT="${UB_INSTALLDIR}$(cups-config --serverroot)" \
    CUPSSERVERBIN="${UB_INSTALLDIR}$(cups-config --serverbin)" \
    soinstall

# elegendő egy szimlink
ln -s gsc "${UB_INSTALLDIR}"/usr/bin/gs

# remove useless broken doc/ symlink - FS#59507
rm -f "${UB_INSTALLDIR}"/usr/share/ghostscript/${UB_VERSION}/doc

# remove unwanted localized manpages
rm -r "${UB_INSTALLDIR}"/usr/share/man/de

# ez egy hagyaték
cp "$UB_COMPILEDIR"/base/gserrors.h "$UB_INSTALLDIR"/usr/include/ghostscript/

# tools
mkdir -p ${UB_INSTALLDIR}/usr/share/ghostpcl
if [ -d 'tools' ]; then
    cp -pr 'tools' "${UB_INSTALLDIR}/usr/share/ghostpcl/"
    cp -pr 'urwfonts' "${UB_INSTALLDIR}/usr/share/ghostpcl/"
    #install -d "${UB_INSTALLDIR}/usr/share/ghostpcl/doc"
    for _doc in 'README.txt' doc/ghost* 'doc/who_owns_what.txt'; do
      install -Dpm644 "${_doc}" -t "${UB_INSTALLDIR}/usr/share/ghostpcl/doc/"
    done
  else # as of 9.18
    cp -pr {xps,pcl}/'tools' "${UB_INSTALLDIR}/usr/share/ghostpcl/"
    cp -pr 'pcl/urwfonts' "${UB_INSTALLDIR}/usr/share/ghostpcl/"
fi

# ijs
cd ijs
ub_install
