#!/bin/sh -eux

# alapinstalláció
make DESTDIR="${UB_INSTALLDIR}" \
    install-gs install-so-gs

make DESTDIR="${UB_INSTALLDIR}" \
    install-gxps install-so-gxps

make DESTDIR="${UB_INSTALLDIR}" \
    install-gpcl6 install-so-gpcl6

# elegendő egy szimlink
rm -v "${UB_INSTALLDIR}"/usr/bin/gs
ln -s gsc "${UB_INSTALLDIR}"/usr/bin/gs

# remove useless broken doc/ symlink - FS#59507
rm -f "${UB_INSTALLDIR}"/usr/share/ghostscript/${UB_VERSION}/doc

# remove unwanted localized manpages
rm -r "${UB_INSTALLDIR}"/usr/share/man/de

# conflicts with libgxps-dev
rm -r "${UB_INSTALLDIR}"/usr/lib/libgxps.so

# ez egy hagyaték
cp "$UB_COMPILEDIR"/base/gserrors.h "$UB_INSTALLDIR"/usr/include/ghostscript/

# ijs
cd ijs
ub_install
