#!/bin/sh -eux

git clone https://github.com/eranif/ctags.git submodules/ctags
git clone https://github.com/eranif/wxdap.git submodules/wxdap
git clone --recursive https://github.com/eranif/cc-wrapper.git submodules/cc-wrapper
git clone https://github.com/jbeder/yaml-cpp.git submodules/yaml-cpp
git clone https://github.com/cubicdaiya/dtl.git submodules/dtl
git clone https://github.com/ggerganov/llama.cpp.git submodules/llama.cpp

cd submodules/wxdap
git checkout 10f57bb
cd ../..

cd submodules/yaml-cpp
git checkout 1b50109
cd ../..

cd submodules/cc-wrapper
git checkout 6771344
cd ../..

ub_compile \
    -DCMAKE_INSTALL_LIBDIR=lib
