#!/bin/sh -eux

ub_compile \
	--libexecdir=/usr/lib \
	--enable-syslog \
	--enable-dynamic \
	--enable-ipv6 \
	--enable-local \
	\
	--enable-slapd \
	--enable-slp \
	--enable-cleartext \
	--enable-crypt \
	--enable-spasswd \
	--enable-rlookups \
	\
	--enable-modules \
	--enable-backends=mod \
	--enable-mdb \
	--enable-perl \
	--disable-ndb \
	--disable-wt \
	\
	--enable-overlays=mod \
	\
	--without-fetch
