#!/bin/sh -eux

# rm -f meson.build

# a meson vala kezelése időnként bugos...
if [ -f meson.build ]; then
ub_compile \
	-Dudev_dir=/usr/lib/udev/ \
	-Dconfig_dhcp_default=internal \
	-Dsession_tracking=systemd \
	-Difupdown=true \
	-Dmodify_system=true \
	-Dconcheck=true \
	-Dselinux=false \
	-Dnmtui=false \
	-Dqt=false \
	-Dbluez5_dun=true \
	-Dpolkit=true
else
ub_compile \
	--with-udev-dir=/usr/lib/udev/ \
	--with-config-dhcp-default=internal \
	--with-session-tracking=systemd \
	--enable-ifupdown \
	--enable-modify-system \
	--enable-concheck \
	--with-selinux=no \
	--with-nmtui=no \
	--disable-qt \
	--enable-bluez5-dun \
	--enable-polkit=yes
fi
