#!/bin/sh -eux

export CC=clang
export CXX=clang++
export AR=llvm-ar
export NM=llvm-nm
export RANLIB=llvm-ranlib
export PYTHON=/usr/bin/python3

cd js/src
export MOZ_OBJDIR=$UB_OBJECTDIR
export RUSTFLAGS="-C embed-bitcode"

cd "$UB_OBJECTDIR"
"$UB_COMPILEDIR"/js/src/configure \
	--prefix=/usr \
    --with-system-icu \
    --with-system-zlib \
    --with-intl-api \
    --enable-shared-js \
    --enable-linker=lld \
    --disable-debug \
    --disable-debug-symbols \
    --disable-jemalloc \
    --disable-optimize \
    --disable-strip
ub_make
