#!/bin/sh -eux

make DESTDIR=$UB_INSTALLDIR install

# Remove static libs
#find "$UB_INSTALLDIR"/usr/lib \( -name "*.a" -o -name "*.o" -o -name "*.p_o" -o -name "*.p_hi" -o -name "*.hi" \) -delete
# Remove obj files, empty-dyrectories
find "$UB_INSTALLDIR"/usr/lib \( -name "*.o" -o -name "*.p_o" \) -delete
find "$UB_INSTALLDIR"/usr/lib -type d -empty -delete

# patchelf, mert nálunk már nincs /lib64, amit a debian még használ
cd $UB_INSTALLDIR/usr/lib/ghc-${UB_VERSION}/bin
for binfile in `ls -1` ;do
     patchelf --set-interpreter /usr/lib/ld-linux-x86-64.so.2 $binfile
done
