#!/bin/sh -eux

ub_install

# remove this example, we dont want to depend on tcsh
rm -f "$UB_INSTALLDIR"/usr/share/doc/util-linux/getopt-example.tcsh

# fix version in .pc files
if [ "$UB_VERSION_HEAD2" = "$UB_VERSION" ]; then
	sed -i "s/^Version: .*$/Version: $UB_VERSION/g" "$UB_INSTALLDIR"/usr/lib/pkgconfig/*.pc
fi
