#!/bin/sh -eux

waf configure \
	--prefix=/usr \
	--confdir=/etc/mpv \
	--enable-cdda \
	--enable-dvb \
	--enable-dvdnav \
	--enable-libarchive \
	--enable-libmpv-shared \
	--disable-build-date \

waf build
