#!/bin/sh -eux

./configure \
    --prefix=/usr \
    --with-lib-path=/lib:/usr/lib:/usr/local/lib \
    --with-pic \
    --with-system-zlib \
    --enable-cet \
    --enable-deterministic-archives \
    --enable-gold \
    --enable-ld=default \
    --enable-lto \
    --enable-plugins \
    --enable-relro \
    --enable-targets=x86_64-pep \
    --enable-threads \
    --disable-gdb \
    --disable-werror

make configure-host
make -e \
	tooldir=/usr
