#!/bin/sh -eux

# git clone https://github.com/KhronosGroup/SPIRV-Headers.git
# mv SPIRV-Headers External/external/
mv External/external/SPIRV-Headers-ba29b3f External/external/SPIRV-Headers

ub_compile \
	-DBUILD_SHARED_LIBS=OFF \
	-DSPIRV_WERROR=OFF
