#!/bin/sh -eux

cd src
ub_install

mkdir -p "$UB_INSTALLDIR"/usr/share/dict
ln -sf /usr/share/cracklib/cracklib-small "$UB_INSTALLDIR"/usr/share/dict/cracklib-small

export PATH="$UB_INSTALLDIR:$PATH"
cracklib-format dicts/cracklib-small | cracklib-packer $UB_INSTALLDIR/usr/share/cracklib/pw_dict
