#!/bin/sh -eux

# kajongg kibobva: python3-twisted >= 16.6.0 függőségű, de nem találja a 21.7.0.-t

for i in *; do
	cd $i
	ub_compile \
	-DCMAKE_PREFIX_PATH=/usr/lib/qt5 \
	-DKDE_INSTALL_USE_QT_SYS_PATHS=ON \
	-DBUILD_TESTING=OFF
	cd ..
done
