#!/bin/sh -eux

make package pkgdir="$UB_COMPILEDIR"/Package

# az installnetpbm.pl nem UHU-kompatíbilis, manuálisan telepítünk

cp -a -r "$UB_COMPILEDIR"/Package/bin "$UB_INSTALLDIR"/usr/
cp -a -r "$UB_COMPILEDIR"/Package/include "$UB_INSTALLDIR"/usr/
cp -a -r "$UB_COMPILEDIR"/Package/lib "$UB_INSTALLDIR"/usr/
cp -a -r "$UB_COMPILEDIR"/Package/sharedlink/* "$UB_INSTALLDIR"/usr/lib/

rm -rf "$UB_INSTALLDIR"/usr/bin/doc.url
rm -rf "$UB_INSTALLDIR"/usr/share/man/web
